const theme = {
  colors: {
    mainColor: 'var(--color-main)',
    titleColor: 'var(--color-title)',
    backgroundColor: 'var(--color-background)',
    secondaryBackgroundColor: 'var(--color-background-secondary)',
    alternativeBackground: 'var(--color-background-alternative)',
    lightSecondaryBackground: 'var(--color-background-light-secondary)',
    lighterSecondaryBackground: 'var(--color-background-lighter-secondary)',
    shareBackground: 'var(--color-background-share)',
    popoverBackground: 'var(--color-background-popover)',
    modalBackground: 'var(--color-background-modal)',
    commentBackground: 'var(--color-background-comment)',
    inputBackground: 'var(--color-background-input)',
    lightText: 'var(--color-text-light)',
    namesakeText: 'var(--color-text-namesake)',
    lightContrast: 'var(--color-contrast-light)',
    darkGray: 'var(--color-gray-dark)',
    gray: 'var(--color-gray)',
    lightGray: 'var(--color-gray-light)',
    purple: 'var(--color-purple)',
    borderColor: 'var(--color-border)',
    lightGreen: 'var(--color-light)',
    hashtag: 'var(--color-hashtag)',
    link: 'var(--color-link)',
    danger: 'var(--color-danger)',
    error: 'var(--color-error)',
    pink: 'var(--color-pink)',
    themeColor: 'var(--color-theme)',
    mainShadow: 'var(--shadow-primary)',
    secondaryShadow: 'var(--shadow-secondary)',
  },
  mdxTheme: {
    background: 'var(--mdxtheme-background)',
    normalFont: 'var(--mdxtheme-text)',
  },
  fonts: {
    display: '"Audiowide", sans-serif',
    primary: '"Exo 2", sans-serif',
  },
};

export default theme;
